ci - increase code in release

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,8 +1,7 @@
 name: Release
 on: { push: { branches: [ main ], tags: [ 'v*' ] } }
 concurrency:
-  group: ${{ github.head_ref || github.ref }}
-  cancel-in-progress: true
+  group: release
 permissions:
   contents: write
 jobs:
@@ -31,23 +30,59 @@ jobs:
 
       - name: Update version code
         run: |
+          current_version=$(grep VERSION_NAME= version.properties | cut -d= -f2)
+          sed -i 's/VERSION_NAME=.*/VERSION_NAME='${current_version}'/g' version.properties
+
           ./gradlew increaseVersionCode
 
           git config user.email "ci-update-version-code[bot]@users.noreply.github.com"
           git config user.name "ci-update-version-code[bot]"
 
           git add version.properties
-          git commit -m 'Increase version code'
+          git commit -m 'Increase version code [skip ci]'
 
-          git push origin ${{ github.ref }}
+          for attempt in {1..5};
+          do
+            if [ "${attempt}" -gt 1 ];
+            then
+              echo "Attempting to rebase (${attempt})"
+              git fetch -a
+              git rebase -X theirs origin/${{ github.ref }}
+              sleep $((attempt * 2))
+            fi
+            if git push origin ${{ github.ref }}; then exit 0; fi
+          done
+
+          echo "Failed to push"
+          exit 1
         if: "!startsWith(github.ref, 'refs/tags/')"
 
       - name: Update version.properties for release
         run: |
           sed -i 's/VERSION_NAME=.*/VERSION_NAME='${GITHUB_REF##*/}'/g' version.properties
-          sed -i 's/VERSION_CODE=.*/VERSION_CODE=1/g' version.properties
-        if: "startsWith(github.ref, 'refs/tags/')"
+          ./gradlew increaseVersionCode
 
+          git config user.email "ci-update-version-code[bot]@users.noreply.github.com"
+          git config user.name "ci-update-version-code[bot]"
+
+          git add version.properties
+          git commit -m 'Increment version for release [skip ci]'
+
+          for attempt in {1..5};
+          do
+            if [ "${attempt}" -gt 1 ];
+            then
+              echo "Attempting to rebase (${attempt})"
+              git fetch -a
+              git rebase -X theirs origin/main
+              sleep $((attempt * 2))
+            fi
+            if git push origin main; then exit 0; fi
+          done
+
+          echo "Failed to push"
+          exit 1
+        if: "startsWith(github.ref, 'refs/tags/')"
 
       - name: Build apk
         run: |
